### ISSUE TITLE
Null points should still be added to polyline

### ISSUE THREAD

**Issue by Maginor** [anboto/Scatter#2]
Hi,
The old functionality of ScatterDraw was so that if there is a Null point in a LinePlot, it will have a hole in the line.
I rely on this functionality, but the changes in DataAddPoints last month made it so that it just draws a line across the gap.

If you want it to do this, can it at least be configurable?
@jakubpawlewicz

**Comment by jakubpawlewicz** [comment]
Aha ok, I wasn't aware of such functionality.

It seems that U++ polygon drawing makes hole if it encounters Null. However, when U++ fills polygon it still makes a vertex in (-inf, -inf) which is wrong. Probably, appropriate painters should be fixed in U++. Then the commit 195f8f1ec12c40bad9ace1e9b2295c8659c2548d can be simply reverted.

I can fix that behaviour at ScatterDraw level, by reverting the mentioned commit and filter out nulls only for DataRange. I will prepare PR.

**Comment by Maginor** [comment]
Thank you, this gives the right behaviour for me.

**Comment by izabala123** [comment]
I am not totally sure about the best behaviour. If you run ScatterDraw_demo_cl, you will get from this vector

`s1 = {{1,14}, {2,65}, {3,29}, {Null,Null}, {5,40}, {6,50}, {7,Null}, {8,25}, {9,10}};`

this plot

![image](https://user-images.githubusercontent.com/38589221/226172818-a74bcc02-c05c-4dff-a944-898f73a38bc1.png)

If x == y == Null, plot line jumps, but if just y == Null, a hole is created.

What would be the best behaviour?

**Comment by Maginor** [comment]
Hi, I am only interested in the case where x is not Null and y is Null, and in that case I want the hole to be created, just like it works now. I will never have Null x values.
I imagine it could be confusing if it didn't create a hole on Null x values, but I can't currently imagine how it would come up in a use case.
In my case, the Null y value typically comes from a missing or deleted sample in a series where you otherwise have samples at regular intervals (so the x value is given).

**Comment by jakubpawlewicz** [comment]
If you want understand how it is done you have to investigate `DrawingFunctions.cpp::DrawPolylineOpa()` functions. I see there `IsNull()` is only applied to points, so if only x or y coordinate is Null it is delegated to `Draw::DrawLine()` or similar U++ interior.
